import {categories,visibleProjects,contactUrl,safeExternal} from './lib.mjs';
export const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const arrow = '<span aria-hidden="true">↗</span>';
export function external(url,label,classes='button secondary') {
  if(!safeExternal(url))return '';
  return `<a class="${classes}" href="${esc(url)}" data-external target="_blank" rel="noopener noreferrer">${label}${arrow}</a>`;
}
export function discussion(project,classes='button primary') {
  return `<a class="${classes}" href="#/contact${project?'?project='+esc(project.id):''}">${project?'Обсудить похожую задачу':'Обсудить задачу'}${arrow}</a>`;
}
function stage(p){return `<span class="stage"><i></i>${esc(p.stage)}</span>`;}
function chips(p){return p.categories.map(c=>`<span>${esc(categories.find(x=>x.id===c)?.label)}</span>`).join('');}
function result(p){return p.resultSummary || p.features[0];}
export function savedResult(example){
  return `<div class="sample-question"><span class="eyebrow">ВОПРОС</span><p>${esc(example.question)}</p></div><div class="sample-answer"><span class="sample-status${example.grounded?'':' no-answer'}">${example.grounded?'Найдены материалы':'Недостаточно информации в базе'}</span><p>${esc(example.answer)}</p></div>${example.sources.length?`<div class="sample-sources"><span class="eyebrow">ИСТОЧНИКИ В БАЗЕ</span><ol>${example.sources.map(s=>`<li><details><summary><strong>${esc(s.title)}</strong><span>${esc(s.section)}</span></summary><p class="source-excerpt">${esc(s.excerpt)}</p></details></li>`).join('')}</ol></div>`:'<p class="sample-empty">В этом сохранённом примере источников нет. В реализации бота можно передать вопрос человеку.</p>'}`;
}
function savedDemo(p){
  if(!p.savedDemo?.examples.length)return '';
  const demo=p.savedDemo;
  return `<div class="saved-demo"><span class="eyebrow">ПРОВЕРЕННЫЕ ПРИМЕРЫ ПОИСКА</span><h3>Вопрос → выдержка → источник</h3><p>${esc(demo.note)}</p><div class="sample-buttons" role="group" aria-label="Сохранённые вопросы">${demo.examples.map((x,i)=>`<button class="sample-button${i===0?' active':''}" data-sample="${i}" aria-pressed="${i===0}">${esc(x.label)}</button>`).join('')}</div><div id="sample-result" aria-live="polite" aria-atomic="true">${savedResult(demo.examples[0])}</div><span class="sample-date">Офлайн-проверка ${esc(demo.checkedOn.split('-').reverse().join('.'))} · без генерации AI</span></div>`;
}
function deliverables(p){
  return p.deliverables?.length?`<div class="case-deliverables"><span class="eyebrow">СОСТАВ РЕАЛИЗАЦИИ</span><h3>Что подготовлено</h3><ul>${p.deliverables.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>Состав похожего проекта согласую с вами под конкретную задачу.</p></div>`:'';
}
function decisions(p){
  return p.decisions?.length?`<div class="case-decisions"><span class="eyebrow">ПОЧЕМУ ТАК</span>${p.decisions.map(x=>`<div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></div>`).join('')}</div>`:'';
}
function localDemo(p){
  return p.localDemo&&/^demos\/[a-z0-9-]+\.html$/.test(p.localDemo.src)?`<div class="local-demo"><div><span class="eyebrow">МОЖНО ПОПРОБОВАТЬ</span><p>${esc(p.localDemo.note)}</p></div><a class="button primary" href="./${esc(p.localDemo.src)}" data-external target="_blank" rel="noopener noreferrer">${esc(p.localDemo.label)}${arrow}</a></div>`:'';
}
export function cover(p,featured=false){
  return `<div class="project-visual ${esc(p.accent)} ${p.cover?'has-image':'typographic'}"><div class="visual-topline"><span>${esc(p.coverLabel)}</span><span aria-hidden="true">${p.cover?'↗':'◇'}</span></div>${p.cover?`<div class="screen-frame"><div class="screen-chrome" aria-hidden="true"><i></i><i></i><i></i><span>${esc(p.title)}</span></div><img src="./${esc(p.cover)}" alt="${esc(p.title)} — ${esc(p.subtitle)}" width="1440" height="900" loading="${featured?'eager':'lazy'}" decoding="async"></div>`:`<div class="monogram" aria-hidden="true">${esc(p.monogram)}<span>·</span></div><div class="concept-lines" aria-hidden="true"><i></i><i></i><i></i></div><span class="visual-caption">${esc(p.subtitle)}</span>`}</div>`;
}
export function card(p,featured=false){
  return `<article class="project-card${featured?' featured-card':''}"><a class="card-link" href="#/project/${esc(p.id)}">${cover(p,featured)}<div class="card-content"><div class="card-top"><span class="eyebrow">${esc(p.type)}</span>${stage(p)}</div><div class="card-heading"><h3>${esc(p.title)}</h3><span class="round-arrow" aria-hidden="true">↗</span></div><p>${esc(p.summary)}</p><div class="card-tags">${chips(p)}</div>${featured?`<div class="card-result"><span aria-hidden="true">↳</span>${esc(result(p))}</div>`:''}</div></a></article>`;
}
export function banner(site,p){return `<section class="contact-banner"><div><span class="eyebrow">ОБСУДИМ ВАШ ПРОЕКТ</span><h2>${p?'Похожая задача?':'Давайте соберём<br>ваше решение.'}</h2><p>Расскажите, как всё устроено сейчас<br>и что хотите изменить.</p></div><div class="banner-action">${external(contactUrl(site,p),'Написать в Telegram','button primary')}${discussion(p,'inline-link')}<span class="contact-caption">Лично отвечаю · @${esc(site.telegram)}</span></div></section>`;}
export function home({site,projects,category}){
  const all=visibleProjects(projects);
  const featured=all.filter(p=>p.featured);
  return `<section class="hero"><div class="hero-copy"><div class="eyebrow hero-kicker"><span class="little-star" aria-hidden="true">✳</span> ЛЕВ · НЕЗАВИСИМЫЙ РАЗРАБОТЧИК</div><h1>Сайты. Боты.<br><span>Автоматизация.</span></h1><p class="hero-description">Разрабатываю под брендом Virentora.<br>От первого экрана до заявки в CRM<br class="desktop-break"> и автоматизации ежедневных задач.</p><div class="hero-actions"><a class="button primary" href="#catalog" data-scroll="catalog">Смотреть проекты<span aria-hidden="true">↓</span></a>${external(contactUrl(site),'Написать мне','button text-button')}</div><div class="hero-signature"><span class="signature-mark" aria-hidden="true">Л</span><div><strong>Лев / Virentora</strong><span>Разработка и общение напрямую</span></div><a href="#/about" aria-label="Обо мне">↗</a></div></div><div class="hero-aside"><div class="aside-title"><span class="eyebrow">СОБИРАЮ ЧАСТИ В СИСТЕМУ</span><span class="aside-index">/ 01</span></div><div class="system-diagram" role="img" aria-label="Сайт или Telegram связаны через логику и API с CRM и данными"><div class="system-inputs"><span>Сайт</span><span>Telegram</span></div><div class="system-connector" aria-hidden="true"></div><div class="system-core"><span class="core-mark" aria-hidden="true">V<span>·</span></span><div><strong>Логика + API</strong><span>Под вашу задачу</span></div><span class="core-arrow" aria-hidden="true">↗</span></div><div class="system-connector" aria-hidden="true"></div><div class="system-outputs"><span>CRM</span><span>Данные</span><span>Уведомления</span></div></div><div class="aside-bottom"><span>Интерфейс → действие → результат</span><span aria-hidden="true">↙</span></div></div></section>
  <div class="expertise-strip" aria-label="Направления работы"><span>Сайты и каталоги</span><i aria-hidden="true">/</i><span>Telegram</span><i aria-hidden="true">/</i><span>CRM и API</span><i aria-hidden="true">/</i><span>AI и данные</span></div>
  ${featured.length?`<section class="featured-section" aria-labelledby="featured-title"><div class="section-heading"><div><span class="eyebrow">ПОДРОБНЫЕ ПРИМЕРЫ</span><h2 id="featured-title">Избранные работы<span class="amber-dot">.</span></h2></div><span class="section-caption">Задача, решение<br>и настоящий интерфейс</span></div><div class="featured-grid">${featured.map(p=>card(p,true)).join('')}</div></section>`:''}
  ${site.taskExamples?.length?`<section class="task-examples" aria-labelledby="task-title"><div class="section-heading"><div><span class="eyebrow">ОТ ЗАДАЧИ К ПРИМЕРУ</span><h2 id="task-title">Что хотите сделать?</h2></div></div><div class="task-grid">${site.taskExamples.filter(x=>all.some(p=>p.id===x.project)).map(x=>`<a href="#/project/${esc(x.project)}"><div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></div><span aria-hidden="true">↗</span></a>`).join('')}</div></section>`:''}
  <section id="catalog" class="catalog" aria-labelledby="catalog-title"><div class="section-heading"><div><span class="eyebrow">ПОДБЕРИТЕ ПРИМЕР ПОД СВОЮ ЗАДАЧУ</span><h2 id="catalog-title">Все проекты <sup>${String(all.length).padStart(2,'0')}</sup></h2></div><span class="section-caption">Сайты, боты и внутренние инструменты</span></div><div class="catalog-controls"><div class="filters" role="group" aria-label="Направление проекта">${categories.map(c=>`<button data-filter="${c.id}" aria-pressed="${category===c.id}" class="filter${category===c.id?' selected':''}">${c.label}<span aria-hidden="true">${visibleProjects(projects,c.id).length}</span></button>`).join('')}</div><p id="filter-status" class="catalog-count" role="status" aria-live="polite">${visibleProjects(projects,category).length} из ${all.length} проектов</p></div><div id="project-grid" class="project-grid">${visibleProjects(projects,category).map(p=>card(p)).join('')}</div></section>
  <section class="about-teaser"><div><span class="eyebrow">ЧЕЛОВЕК ЗА РАБОТАМИ</span><div class="teaser-monogram" aria-hidden="true">V<span>·</span></div></div><div><h2>Привет, я Лев<span class="amber-dot">.</span></h2><p>Работаю самостоятельно: разбираюсь в задаче, собираю интерфейс, связываю сервисы и проверяю результат. Со мной можно поговорить напрямую.</p><div class="teaser-values"><span>Понятный объём</span><span>Проверяемые сценарии</span><span>Передача результата</span></div><a href="#/about" class="inline-link">Подробнее о подходе${arrow}</a></div></section>${banner(site)}`;
}
function caseSection(id,num,label,title,body){return `<section id="${id}" class="case-section"><span class="eyebrow">${num} / ${label}</span><h2>${title}</h2>${body}</section>`;}
export function projectView(p,{site,projects}){
  const index=p.gallery.findIndex(g=>g.src===p.cover);
  const next=visibleProjects(projects).filter(x=>x.id!==p.id).sort((a,b)=>Number(b.categories.some(c=>p.categories.includes(c)))-Number(a.categories.some(c=>p.categories.includes(c)))).slice(0,2);
  const walk=p.walkthrough || [];
  const scenario=`<ol class="steps">${p.steps.map((s,i)=>`<li><span class="step-number">0${i+1}</span><div><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p></div></li>`).join('')}</ol>${walk.length?`<div class="walkthrough"><span class="eyebrow">СОХРАНЁННЫЙ ПРИМЕР</span><p>Выберите шаг и посмотрите его настоящий экран.</p><div class="walk-tabs" role="group" aria-label="Экраны сценария">${walk.map((w,i)=>`<button data-walk="${i}" class="walk-tab${i===0?' active':''}" aria-pressed="${i===0}">${esc(w.label)}</button>`).join('')}</div><figure class="walk-figure"><button data-gallery="${walk[0].image}" aria-label="Увеличить экран сценария"><img src="./${esc(p.gallery[walk[0].image].src)}" alt="${esc(p.gallery[walk[0].image].caption)}" loading="lazy"><span aria-hidden="true">⤢</span></button><figcaption>${esc(p.gallery[walk[0].image].caption)}</figcaption></figure></div>`:''}`;
  return `<div class="case-breadcrumb"><button class="back-link" data-action="back">← Все проекты</button><span class="eyebrow">${esc(p.coverLabel)}</span></div><article class="case-page"><div class="case-topline"><span class="eyebrow">${esc(p.type)}</span>${stage(p)}</div><div class="case-heading"><div><h1>${esc(p.title)}<span class="amber-dot">.</span></h1><p class="case-subtitle">${esc(p.subtitle)}</p></div><button class="button secondary share-button" data-action="share" aria-label="Ссылка на проект">Поделиться${arrow}</button></div><p class="case-intro">${esc(p.summary)}</p><div class="case-actions">${external(contactUrl(site,p),'Написать о похожей задаче','button primary')}${discussion(p,'button secondary')}${p.localDemo?`<a class="button secondary" href="#case-proof" data-scroll="case-proof">Попробовать пример<span aria-hidden="true">↓</span></a>`:''}${p.links.map(l=>external(l.url,esc(l.label))).join('')}</div>
  ${p.cover?`<button class="case-hero${p.heroCrop?' crop-hero':''}" data-gallery="${index}" aria-label="Увеличить изображение проекта ${esc(p.title)}"><img src="./${esc(p.cover)}" alt="${esc(p.gallery[index].caption)}"><span>Посмотреть интерфейс в деталях<span aria-hidden="true">⤢</span></span></button>`:cover(p)}
  <div class="case-summary"><span class="eyebrow">РЕЗУЛЬТАТ В ОДНОМ ПРЕДЛОЖЕНИИ</span><p>${esc(result(p))}</p><span class="summary-note">${esc(p.evidenceLabel || 'Реализация описана в материалах проекта')}</span></div>
  ${p.parts?.length?`<section class="case-components" aria-label="Стадии частей проекта">${p.parts.map(x=>`<div><span class="eyebrow">${esc(x.name)}</span><p>${esc(x.stage)}</p></div>`).join('')}</section>`:''}
  <div class="case-body"><aside class="case-facts"><nav class="case-toc" aria-label="Разделы кейса"><span class="eyebrow">В ЭТОМ КЕЙСЕ</span><a href="#case-task" data-scroll="case-task">01 <span>Задача</span></a><a href="#case-role" data-scroll="case-role">02 <span>Решение</span></a><a href="#case-scenario" data-scroll="case-scenario">03 <span>Сценарий</span></a><a href="#case-proof" data-scroll="case-proof">04 <span>Результат</span></a></nav><div><span class="eyebrow">ДЛЯ КОГО</span><p>${esc(p.audience)}</p></div><div><span class="eyebrow">ИНСТРУМЕНТЫ</span><div class="stack">${p.stack.map(s=>`<span>${esc(s)}</span>`).join('')}</div></div><div><span class="eyebrow">МАТЕРИАЛЫ ПРОВЕРЕНЫ</span><p>${esc(p.verifiedOn.split('-').reverse().join('.'))}</p></div></aside><div class="case-narrative">${caseSection('case-task','01','ЗАДАЧА','Что нужно было решить',`<p>${esc(p.task)}</p>`)}${caseSection('case-role','02','РЕШЕНИЕ','Что я сделал',`<p>${esc(p.role)}</p><ul class="feature-list">${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul>${decisions(p)}`)}${caseSection('case-scenario','03','СЦЕНАРИЙ','Как это работает',scenario)}${caseSection('case-proof','04','ПРОВЕРКА','Наблюдаемый результат',`<div class="proof-box"><span class="proof-mark" aria-hidden="true">↳</span><p>${esc(p.proof)}</p></div>${savedDemo(p)}${localDemo(p)}${deliverables(p)}`)}</div></div>
  ${p.gallery.length?`<section class="case-gallery"><div class="section-heading"><div><span class="eyebrow">ЭКРАНЫ И ДЕТАЛИ</span><h2>Материалы проекта<span class="amber-dot">.</span></h2></div><span class="section-caption">Откройте на весь экран</span></div><div class="gallery-grid">${p.gallery.map((g,i)=>`<figure><button data-gallery="${i}" aria-label="Увеличить: ${esc(g.caption)}"><img src="./${esc(g.src)}" alt="${esc(g.caption)}" loading="lazy" decoding="async"><span aria-hidden="true">⤢</span></button><figcaption>${esc(g.caption)}</figcaption></figure>`).join('')}</div></section>`:''}
  ${p.video?`<section><h2>Видео проекта</h2><video controls preload="metadata" playsinline src="${esc(p.video)}">Ваш браузер не поддерживает видео.</video></section>`:''}
  <section class="limits"><div><span class="eyebrow">ПРОИСХОЖДЕНИЕ И ГРАНИЦЫ</span><h2>Контекст проекта</h2></div><ul>${p.limits.map(l=>`<li>${esc(l)}</li>`).join('')}</ul></section>${banner(site,p)}<section class="related"><div class="section-heading"><div><span class="eyebrow">ПРОДОЛЖИТЬ ЗНАКОМСТВО</span><h2>Ещё работы</h2></div><a href="#/projects" class="inline-link">Все проекты${arrow}</a></div><div class="related-grid">${next.map(x=>`<a class="related-link" href="#/project/${x.id}"><span class="related-monogram ${esc(x.accent)}">${esc(x.monogram)}</span><div><span class="eyebrow">${esc(x.coverLabel)}</span><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p></div><span aria-hidden="true">↗</span></a>`).join('')}</div></section></article>`;
}
export function about({site}){return `<section class="text-page"><span class="eyebrow">ЧЕЛОВЕК ЗА ПРОЕКТАМИ</span><h1>Привет, я Лев<span class="amber-dot">.</span></h1><p class="large-intro">Разрабатываю технические решения<br>для бизнеса под брендом Virentora.</p><div class="about-layout"><div class="identity-card"><span class="identity-mark" aria-hidden="true">V<span>·</span></span><h2>Лев / Virentora</h2><p>Независимый разработчик</p><span class="eyebrow">ОТ ИДЕИ ДО РЕАЛИЗАЦИИ</span></div><div><p>Работаю самостоятельно и общаюсь с заказчиками напрямую. Разбираюсь в задаче, собираю интерфейс и настраиваю то, что должно происходить после нажатия кнопки.</p><p>Использую ИИ для разработки, анализа и подготовки материалов. Проверяю результат на конкретных сценариях.</p><h2>Чем могу помочь</h2><ul class="feature-list"><li>Сайт, лендинг или каталог с понятным путём к обращению</li><li>Telegram-бот для услуг, заявок или работы с документами</li><li>Интеграция форм, CRM, таблиц и уведомлений</li><li>Автоматизация повторяющихся действий и обработка данных</li></ul></div></div><section class="work-process"><span class="eyebrow">КАК ПРОХОДИТ РАБОТА</span><h2>Сначала задача. Затем решение.</h2><div class="process-grid"><div><span>01</span><h3>Разобраться</h3><p>Обсуждаем текущий процесс, ограничения и нужный результат.</p></div><div><span>02</span><h3>Согласовать</h3><p>Определяем объём, сценарии, этапы и критерии готовности.</p></div><div><span>03</span><h3>Собрать и проверить</h3><p>Проходим путь пользователя, проверяем результат и готовим передачу.</p></div></div></section><div class="handoff-note"><span class="eyebrow">ЧТО ОСТАЁТСЯ У ВАС</span><p>Согласованный результат, материалы и понятная инструкция по работе с решением. Состав передачи зависит от проекта и обсуждается заранее.</p></div><p class="origin-note">В портфолио есть демонстрационные проекты и собственные инструменты. Тип работы и границы готовности указаны в каждом кейсе.</p>${banner(site)}</section>`;}
export function contact({site,projects,route,brief}){
  const p=projects.find(x=>x.id===route.project && x.published);
  return `<section class="contact-page"><span class="eyebrow">ДАВАЙТЕ ПОЗНАКОМИМСЯ</span><h1>Начнём<br>с вашей задачи<span class="amber-dot">.</span></h1><p class="large-intro">Напишите, что хотите сделать.<br>Обсудим объём, подход и следующий шаг.</p>${p?`<div class="contact-context"><span class="eyebrow">ВАС ЗАИНТЕРЕСОВАЛО</span><a href="#/project/${p.id}">${esc(p.title)}${arrow}</a><p>Добавлю название проекта в начало сообщения.</p></div>`:''}<div class="contact-grid"><div class="message-composer"><span class="eyebrow">МОЖНО ПОДГОТОВИТЬ СООБЩЕНИЕ ЗДЕСЬ</span><h2>Что хотите сделать?</h2><p id="brief-help">Пара предложений о задаче, текущем процессе и желаемом результате. Заполнение необязательно.</p><label for="project-brief">Ваша задача</label><textarea id="project-brief" maxlength="2000" rows="6" placeholder="Например: нужен каталог услуг, а заявки должны приходить в Telegram и CRM…" aria-describedby="brief-help brief-count">${esc(brief)}</textarea><div class="composer-bottom"><span id="brief-count">${brief.length} / 2000</span><button class="inline-link" data-action="clear-brief">Очистить</button></div><div class="composer-actions">${external(contactUrl(site,p,brief),site.telegram?'Перейти в Telegram':'Написать на email','button primary send-brief')}<button class="button secondary" data-action="copy-brief">Скопировать текст</button></div><p class="composer-note">Текст сохранится в этой вкладке. Сообщение отправите сами в диалоге.</p></div><div class="contact-options"><div class="primary-contact"><span class="eyebrow">ЛИЧНЫЙ ДИАЛОГ</span><h2>${site.telegram?'Telegram':'Email'}</h2><p>${site.telegram?'@'+esc(site.telegram):esc(site.email)}</p>${external(contactUrl(site,p),'Написать сразу','button secondary')}<span class="contact-note">Общаетесь со мной напрямую.</span></div><div class="other-contacts"><div><span class="eyebrow">ЕСЛИ УДОБНЕЕ ПОЧТОЙ</span><a class="email-link" href="mailto:${esc(site.email)}?subject=${encodeURIComponent(p?'Проект: '+p.title:'Задача для Virentora')}">${esc(site.email)}${arrow}</a><button class="inline-link" data-action="copy-email">Скопировать email</button></div><div><span class="eyebrow">ОСНОВНОЙ САЙТ</span>${external(site.website,'virentora.com','inline-link')}</div></div></div></div></section>`;
}
export function missing(){return '<section class="text-page empty-state"><span class="eyebrow">404 / СТРАНИЦА НЕ НАЙДЕНА</span><h1>Этот проект пока недоступен.</h1><p>Возможно, ссылка устарела или работа ещё готовится к показу.</p><a class="button primary" href="#/projects">К открытым проектам ↗</a></section>';}
